"""initial

Revision ID: 5ac8b5ff8afc
Revises: 
Create Date: 2024-07-14 17:31:47.455273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ac8b5ff8afc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=200), nullable=True))

    with op.batch_alter_table('nurses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=200), nullable=True))

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_column('address')

    with op.batch_alter_table('nurses', schema=None) as batch_op:
        batch_op.drop_column('address')

    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_column('address')

    # ### end Alembic commands ###
