"""tasks

Revision ID: 8fd7af8b8512
Revises: 9eb3a8d2ad8a
Create Date: 2024-07-17 00:12:10.219249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fd7af8b8512'
down_revision = '9eb3a8d2ad8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('patient_id', sa.String(length=100), nullable=True),
    sa.Column('doctor_id', sa.String(length=100), nullable=True),
    sa.Column('nurse_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    # ### end Alembic commands ###
