"""relationships

Revision ID: bae3a199ca5c
Revises: fe89942fe84e
Create Date: 2024-07-17 23:30:45.892974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bae3a199ca5c'
down_revision = 'fe89942fe84e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'patients', ['patient_id'], ['id'])
        batch_op.create_foreign_key(None, 'doctors', ['doctor_id'], ['id'])

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'patients', ['patient_id'], ['id'])
        batch_op.create_foreign_key(None, 'doctors', ['doctor_id'], ['id'])
        batch_op.create_foreign_key(None, 'nurses', ['nurse_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
