"""booking


Revision ID: fe89942fe84e
Revises: 8fd7af8b8512
Create Date: 2024-07-17 00:24:38.629276

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fe89942fe84e'
down_revision = '8fd7af8b8512'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('patient_id', sa.String(length=100), nullable=False),
    sa.Column('doctor_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('doctor_id',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('doctor_id',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)

    op.drop_table('bookings')
    # ### end Alembic commands ###
